### ISSUE TITLE
HTTPS certificates are not mounted into Local Beach Nginx proxy

### ISSUE THREAD

**Issue by robertlemke** [flownative/localbeach#13]
After setting up Local Beach for HTTPS with `beach setup-https`, certificates are created in `/usr/local/lib/localbeach/Certificates`. This directory is mounted into the Local Beach Nginx container as `/etc/nginx/certs`. However, the directory may remain empty, because Docker Desktop (on Mac OS) is configured so that only specific directories may be mounted into containers – and `/usr/local/lib` is not among them.

There is no error message, the directory in the Nginx container just remains empty even though it appears to be mounted.

As a workaround, you may enable `/usr/local/lib/localbeach` in Docker Desktop:

<img width="1152" alt="docker-desktop-enable-file-sharing" src="https://user-images.githubusercontent.com/95582/96423501-b409c480-11f9-11eb-844a-9bf161d1a225.png">

However, in order to simplify setup for users, we should store certificates in `~/Library/Application Support…` if possible.

I haven't done this earlier, because `beach setup-https` cannot easily know that path (because it can be a different path when Local Beach is not running on Mac OS). We need to find a better solution there …

**Comment by kdambekalns** [comment]
Given the (potentially) different location used for Homebrew things on Linux (see #6), we seem to need a well-known place to store the place things are stored… 🙄

**Comment by robertlemke** [comment]
Yes. Or a well-known place where we can find a pointer to the place where things are stored. Or we hard-code this path depending on the platform.

Actually, I think it wouldn't be too daring to hardcode "~/Library/Application Support…" into the darwin binary. What do you think?

We could do that via ld flags.

**Comment by kdambekalns** [comment]
> Or we hard-code this path depending on the platform.

Yep, for Darwin that would work. And when simply using something below `~` we could use something similar for Linux, too.

Just when relying on the "lib path" from (Home|Linux)brew we need to deal with some uncertainty. Maybe query an env for those cases?

**Comment by robertlemke** [comment]
Released as [v1.5.0](https://github.com/flownative/localbeach/releases/tag/v1.5.0%2B1)
