### ISSUE TITLE
Removal / move of directories on host are not synced to container volume

### ISSUE THREAD

**Issue by robertlemke** [flownative/localbeach#19]
I renamed a directory "Legacy" to "Something" and then found the following error in the devkit container output:

```devkit_1     | rm: cannot remove '/application/DistributionPackages/Acme.SiteResources/Private/Legacy': Is a directory```

We should check the sync script and make sure that directories are detected as such and then removed with rmdir.

**Comment by kdambekalns** [comment]
The code is in https://github.com/flownative/docker-localbeach-devkit/blob/master/root-files/opt/flownative/sync/bin/watch.sh and it should be doing the righ thing for directories in https://github.com/flownative/docker-localbeach-devkit/blob/24fcdc8c51cbf587ddc71f26fa7b8b667b06743b/root-files/opt/flownative/sync/bin/watch.sh#L33-L34

**Comment by kdambekalns** [comment]
TIL: no `CREATE,ISDIR` is ever emitted…

**Comment by kdambekalns** [comment]
I could not reproduce this now, but even things that broke for me reliably so far(1), do now work.

(1) `yarn install` or building frontend assets including the removal of all build artifacts

**Comment by kdambekalns** [comment]
This is the log of what failed for you:

```
[debug] Sync: CREATE /application-on-host/Legacy
[debug] Sync: -> [ -f /application-on-host/Legacy ] && cp -pLf '/application-on-host/Legacy' '/application/Legacy' ; [ -d /application-on-host/Legacy ] && cp -rpLf '/application-on-host/Legacy' '/application'
[debug] Sync: CREATE /application-on-host/Legacy/foo
[debug] Sync: -> [ -f /application-on-host/Legacy/foo ] && cp -pLf '/application-on-host/Legacy/foo' '/application/Legacy/foo' ; [ -d /application-on-host/Legacy/foo ] && cp -rpLf '/application-on-host/Legacy/foo' '/application/Legacy'
[debug] Sync: DELETE,ISDIR /application-on-host/Legacy
[debug] Sync: -> rm -rf '/application/Legacy'
[debug] Sync: CREATE /application-on-host/Something
[debug] Sync: -> [ -f /application-on-host/Something ] && cp -pLf '/application-on-host/Something' '/application/Something' ; [ -d /application-on-host/Something ] && cp -rpLf '/application-on-host/Something' '/application'
```
