### ISSUE TITLE
Certificate directory is not created, setup uses wrong $HOME

### ISSUE THREAD

**Issue by hphoeksma** [flownative/localbeach#21]
Fresh install of 1.5.0+1, running https-setup gives an error that the certificates directory doesn't  exist.

Manually adding the directory works.

**Comment by kdambekalns** [comment]
I had to run `beach setup` manually for it to appear. Then again, I forgot to do `beach down` before upgrading, maybe that blocked something…

**Comment by hphoeksma** [comment]
I did do a beach down before uninstalling and reinstalling. 
Manually running setup I haven't tried, but a good idea next time.

**Comment by kdambekalns** [comment]
The setup command is run during install, but… installs into the wrong location:

From `~/Library/Logs/Homebrew/localbeach/01.beach`:
```
2020-11-16 20:33:56 +0100

/usr/local/Cellar/localbeach/v1.5.0+1/bin/beach
setup

level=debug msg="setting up Local Beach with base path /private/tmp/localbeach-20201116-22955-btof2/.brew_home/Library/Application Support/Flownative/Local Beach/"
level=debug msg="creating directory for certificates at /private/tmp/localbeach-20201116-22955-btof2/.brew_home/Library/Application Support/Flownative/Local Beach/Nginx/Certificates/"
level=debug msg="creating directory for databases at /private/tmp/localbeach-20201116-22955-btof2/.brew_home/Library/Application Support/Flownative/Local Beach/MariaDB"
```

**Comment by kdambekalns** [comment]
I'd say this is a conceptual issue. Homebrew installs software "for all users", so we should move the setup step to be a manual one. After all, if a second user on a machine wanted to use it, she'd need her own DB directory and it would be counter-intuitive to "install Local Beach again", to be able to set it up. WDYT, @robertlemke?
