### ISSUE TITLE
docker-compose file is missing on clean install

### ISSUE THREAD

**Issue by hphoeksma** [flownative/localbeach#22]
Fresh install of 1.5.0+1, running beach start/down gives an error that the docker-compose.yml doesn't  exist.

Manually adding the file works.

**Comment by DavidSporer** [comment]
I had the same error after an upgrade. Adding the file from here worked: https://github.com/flownative/localbeach/blob/master/~/Library/Application%20Support/Flownative/Local%20Beach/docker-compose.yml

**Comment by kdambekalns** [comment]
This is essentially a duplicate of #21
