### ISSUE TITLE
Symlink is gone after composer update

### ISSUE THREAD

**Issue by robertlemke** [flownative/localbeach#25]
In GitLab by @markusguenther on Jul 12, 2019, 11:19

The current best practice is to have a DistributionPackages folder and then symlink the packages.
I also do that and at the beginning everything is fine.

From time to time I had the issue that in the container the symlink was gone and the code was just copied. So that the sync did not work anymore.

After some days of monitoring I now can say that this always happens when I execute a composer update package from the guest system. At the moment I always go inside the container and fix that for me.

I use:
- Mac with MacOS 10.14.5 
- docker version 18.09.3
- zsh 5.3
- composer version 1.7.2

**Comment by kdambekalns** [comment]
While I have seen some sync issues after Composer operations, the "symlink disappearance" hasn't been happening to me for a long time. I'll close this, feel free to reopen, if needed. /cc @markusguenther

**Comment by markusguenther** [comment]
Since the new beach client it seems to be no issue anymore. Created the issue quite some time ago ;)

🙏
