### ISSUE TITLE
Display synchronisation status on local:up

### ISSUE THREAD

**Issue by robertlemke** [flownative/localbeach#31]
In GitLab by @robertlemke on Dec 3, 2018, 09:12

When a Local Beach container is started with `beach local:up` or `beach local:start`, files are being synchronized from the host to the PHP container. The webserver should display at least a message, or preferably a progress bar, which tells Local Beach users that everything is fine, it's just that files still need to be copied.

**Comment by kdambekalns** [comment]
This will no longer be needed with #41…
