### ISSUE TITLE
Provide ARM64 support for MacOS using Apple's Mx chip set 

### ISSUE THREAD

**Issue by robertlemke** [flownative/localbeach#32]
The Docker images needed for Local Beach are currently only provided as AMD64 builds. In order to support the latest Mac models, we need to provide them as ARM64 as well.

The following images need to be upgraded:
- [x] flownative/localbeach-nginx-proxy
- [x] flownative/redis
- [x] flownative/localbeach-devkit
- [x] flownative/php
- [x] flownative/beach-php
- [x] flownative/nginx
- [ ] [hipages/php-fpm_exporter](https://github.com/hipages/php-fpm_exporter)
- [x] blackfire/blackfire

**Comment by robertlemke** [comment]
flownative/localbeach-nginx-proxy is built for ARM64 since [v0.3.0](https://github.com/flownative/docker-localbeach-nginx-proxy/tree/v0.3.0%2B10).

**Comment by robertlemke** [comment]
All mentioned images are now built for ARM64 as well.

**Comment by robertlemke** [comment]
uhum, I probably forgot one image: PHP. So re-opening this issue …

**Comment by kdambekalns** [comment]
Working fine by now…
