### ISSUE TITLE
Network should be declared as external

### ISSUE THREAD

**Issue by robertlemke** [flownative/localbeach#39]
When doing a `beach stop -r` or `beach restart`, essentially Local Beach does a `docker compose down` which tries to remove the network declared in the `.localbeach.docker-compose.yaml`. This causes the following error:

```
ERROR: error while removing network: network local_beach id … has active endpoints
```

If we declared the network as external, it would be omitted and not result in an error ([see documentation](https://docs.docker.com/compose/reference/down/)).

**Comment by kdambekalns** [comment]
Fixed by now, see also #33
