### ISSUE TITLE
Wrong example in resource-download help

### ISSUE THREAD

**Issue by robertlemke** [flownative/localbeach#42]
The help screen of `resource-download` shows a wrong example for namespace:

> The project namespace of the Beach instance to download from, eg. 'project-123abc45-def6-7890-abcd-1234567890ab'

The actual namespace would be 'project-123abc45-def6-7890-abcd-1234567890ab'

**Comment by kdambekalns** [comment]
Looking at the code the help shows `project-123abc45-def6-7890-abcd-1234567890ab` as the example. The issue description mentions the exact same string twice. So… what should be done? 😎

**Comment by robertlemke** [comment]
Okay, uhum, what I *meant* was that the actual namespace would be:

`beach-project-123abc45-def6-7890-abcd-1234567890ab` 

instead of

`project-123abc45-def6-7890-abcd-1234567890ab`

And, for legacy projects, it's even just "beach". 💫

**Comment by kdambekalns** [comment]
> And, for legacy projects, it's even just "beach".

That's already mentioned in the (general) help text of the command…

**Comment by kdambekalns** [comment]
Like this, then.
