### ISSUE TITLE
Update MariaDB to 10.5

### ISSUE THREAD

**Issue by kdambekalns** [flownative/localbeach#5]
Currrently using 10.2, but since on Beach we have MySQL 5.7 we should update to MariaDB 10.5 for feature parity.

https://github.com/flownative/localbeach/blob/8b399ec83216c53c92b62fedcc9ed7557cd219b8/assets/local-beach/docker-compose.yml#L20

After an upgrade `mysql_upgrade` needs to be run, possibly add to startup so it's done automagically?

See #2 for the basics and https://github.com/flownative/localbeach-phar/issues/20 for the "sister issue".

**Comment by kdambekalns** [comment]
People starting out or switching to the new Go-based client have 10.5 by now. Those upgrading might need the update, still…

**Comment by robertlemke** [comment]
Anyone who needs 10.5 should migrate to the Go client by now.
