### ISSUE TITLE
resource-download creates wrong structure locally

### ISSUE THREAD

**Issue by kdambekalns** [flownative/localbeach#56]
Since #45 the downloaded files ended up in a struture like this:

```
Data/Persistent/Resources
├── 0
│   ├── 1
│   │   ├── 0
│   │   │   └── 1010152dbf465371a9329a34c1a2cf6b31427b352
│   │   │       └── All tests configuration-250x153.png
│   │   └── 5
│   │       └── 50155f33907e1dedca6892ee7184559df22e4612f
│   │           └── IMG_20140329_175546-1000x291.jpg
```

But this would be correct:

```
Data/Persistent/Resources
├── 0
│   ├── 1
│   │   ├── 0
│   │   │   └── 1
│   │   │       └── 010152dbf465371a9329a34c1a2cf6b31427b352
│   │   └── 5
│   │       └── 5
│   │           └── 0155f33907e1dedca6892ee7184559df22e4612f
```

**Comment by dlubitz** [comment]
This is still (or again) broken to me.

https://github.com/flownative/localbeach/blob/d9af8b5303903b513a4fd68e32443216ec30dcd4/cmd/beach/cmd/resource-download.go#L116

The `filepath.Dir()` cut of the last element of the hash. So it creates just 3 levels of hash-folders.

If I remove that, it works fine:

```diff
- targetPath := filepath.Dir(filepath.Join(resourcesPath, getRelativePersistentResourcePathByHash(attributes.Name)))
+ targetPath := filepath.Join(resourcesPath, getRelativePersistentResourcePathByHash(attributes.Name))
```

**Comment by dlubitz** [comment]
I guess this one re-introduced it:
https://github.com/flownative/localbeach/blame/d9af8b5303903b513a4fd68e32443216ec30dcd4/cmd/beach/cmd/resource-download.go#L116
