### ISSUE TITLE
Localbeach setup on Ubuntu 18.04.4

### ISSUE THREAD

**Issue by regniets** [flownative/localbeach#6]
Installed localbeach on ubuntu with an existing localbeach installation (phar beach-cli). Did not work ootb, had to do some manual stuff.
1. Install homebrew. Homebrew will install on either
/home/linuxbrew/.linuxbrew 
/home/[user]/.linuxbrew
Chose user directory (non-recommended though)
2. Removed existing local_beach_* docker containers (based on different docker-compose.yml) and old beach-cli manually
3. `beach setup --database-folder ~/.Flownative/LocalBeach/MariaDB --docker-folder /home/[user]/.linuxbrew/lib/localbeach` should have worked, but exited without any message
4. `beach start` threw "FATAL failed to check for running containers"
5. started local_beach_* containers manually (docker-compose up -d)
6. still fatal error on `beach start`, checked into https://github.com/flownative/localbeach/blob/d7ca06507a6d8dc13478194ed7389dda3ac70048/cmd/beach/cmd/start.go#L95
7. symlinked docker-compose.yml to /usr/local/lib/localbeach
8. Running

**Comment by kdambekalns** [comment]
@regniets Two questions:

- did `beach setup …` create `~/.Flownative/LocalBeach/MariaDB` and `/home/[user]/.linuxbrew/lib/localbeach/docker-compose.yml`? If it did, it worked as expected.
- does Homebrew provide an environment variable under Linux that can be used to find the "install base" (`/home/[user]/.linuxbrew` in your case?)

**Comment by kdambekalns** [comment]
@regniets Expanding on the second questions above, do you have `$HOMEBREW_PREFIX` set to `/home/[user]/.linuxbrew`?

**Comment by regniets** [comment]
on `did beach setup … create ~/.Flownative/LocalBeach/MariaDB and /home/[user]/.linuxbrew/lib/localbeach/docker-compose.yml? If it did, it worked as expected.`

It looks like - the folders were present, if they havent been added by the previous localbeach (phar) Version which had been installed.

**Comment by regniets** [comment]
> @regniets Expanding on the second question above, do you have `$HOMEBREW_PREFIX` set to `/home/[user]/.linuxbrew`?

Yes, it is. 
While homebrew tells me the following:
`Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).`

This was meant by "non-recommended" :)

**Comment by sbruggmann** [comment]
So i had a look at again too. My goal was to get NeosIo running on Ubuntu 20.04 without homebrew and without previous beach installation.

1. Clone this repository, run `make` and copy `beach` to `~/bin/beach`.
2. Copy `/{path_to_localbeach_repo}/assets/local-beach/docker-compose.yml` to `/usr/local/lib/localbeach/docker-compose.yml` and fix write access `sudo chmod o+w /usr/local/lib/localbeach/docker-compose.yml`.
3. Executed `beach setup --database-folder ~/.Flownative/LocalBeach/MariaDB --docker-folder /usr/local/lib/localbeach`.

**Works :-)**

Off topic:

To get NeosIo finally running, i had to go into the container `beach exec /bin/bash` after `beach start` and..
1. download composer `curl https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer |  php --` manually and run `./composer.phar install`
2. `./flow flow:cache:flush; ./flow cache:warmup`. better once too much than too little.
3. import the site `./flow site:import --package-key Neos.NeosIo` etc.

**Comment by kdambekalns** [comment]
Closing this… I hope it works on newer Ubuntu versions and 18.04 is quite old…
