### ISSUE TITLE
Implement "localbeach:upgrade" command

### ISSUE THREAD

**Issue by kdambekalns** [flownative/localbeach#7]
Essentially this is:

- `docker-compose -f /usr/local/lib/beach-cli/localbeach/docker-compose.yml stop`
- `docker-compose -f /usr/local/lib/beach-cli/localbeach/docker-compose.yml pull`
- `docker-compose -f /usr/local/lib/beach-cli/localbeach/docker-compose.yml start`

**Comment by robertlemke** [comment]
May rather call this ´beach restart` instead? And with an optional `--remove` flag?

**Comment by kdambekalns** [comment]
Note: `beach restart` exists by now (see https://github.com/flownative/localbeach/commit/e5c5d1b53e0da2d9fbaa62e5c314aaf140cb0e42 and https://github.com/flownative/localbeach/commit/66c4e75ae150a1463a641a98e9c5fa16c80defa6), but does not target the reverse proxy and database server.

**Comment by robertlemke** [comment]
`beach down && beach start` currently does what's necessary to upgrade. So maybe we don't need this command at all.
