### ISSUE TITLE
Reverse loading order of environment files

### ISSUE THREAD

**Issue by kdambekalns** [flownative/localbeach#80]
Due to the order of files in https://github.com/flownative/localbeach/blob/27c19379f799449b3ac3038954a961849d743b2b/pkg/beachsandbox/helpers.go#L56 one cannot override a variable from `localbeach.dist.env` in one of the other files.

Or I am too stupid to see my error…

Should we revert the order, or was this a very conscious choice?

**Comment by robertlemke** [comment]
It was a conscious choice back then but it probably does not make any sense.

**Comment by kdambekalns** [comment]
I can prepare a PR to revert the order, if you like.
